<?php
/* @var $this View */
?>
<h1>Тестовое задание: &laquo;<?=$this->caption?>&raquo;</h1>

<?=$this->description?>

<p>Требования к заданию:</p>
<ol><li><?=join('</li><li>', $this->requirements)?></li></ol>

<p>Порядок выполнения задания:</p>
<ol><li><?=join('</li><li>', $this->tasks)?></li></ol>

<p>Критерии оценки задания:</p>
<ol><li><?=join('</li><li>', $this->rating)?></li></ol>

<p>Советы:</p>
<ol><li><?=join('</li><li>', $this->hints)?></li></ol>